name = "oss"
main = "src/main.js"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 */6 * * *"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "storage"

[vars]
SCHEDULED = 24
